<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Sentimo\ReviewAnalysis\ViewModel\ProductContext $productContextViewModel */
$productContextViewModel = $block->getProductContextViewModel();
$product = $productContextViewModel?->getProduct();
$productDescription = $productContextViewModel->getProductDescription($product);

/** @var \Sentimo\ReviewAnalysis\ViewModel\HelperWidget $helperWidgetViewModel */
$helperWidgetViewModel = $block->getHelperWidgetViewModel();

$configJson = $helperWidgetViewModel->getConfigJson([
    'productName' => $product?->getName(),
    'productPrice' => $product?->getFinalPrice(),
    'productPriceCurrency' => $productContextViewModel?->getCurrencyCode(),
    'productDescription' => $productDescription ? $block->stripTags($productDescription) : null,
    'productType' => $productContextViewModel?->getAttributeSetName($product),
]);
?>

<script>
    require(['jquery', 'sentimoWidget'], function ($, Sentimo) {
        'use strict';

        $(document).ready(function () {
            Sentimo.reviewHelper(<?= /* @noEscape */ $configJson ?>);
        });
    });
</script>
